### ISSUE TITLE
怎么加入？

### ISSUE THREAD

**Issue by lancelot-Yagami** [ng-fukgin/carla_zh_CN#1]
你好，请问怎么加入参与翻译

**Comment by ng-fukgin** [comment]
> 你好，请问如何参与


你可以先fork这个仓库，翻译完成之后发送pull request请求，我同意一些。好像有个团队协作的，我不太会弄.

**Comment by lancelot-Yagami** [comment]
应该要有todo list 的，还有任务分配，不然容易做重复工

**Comment by ng-fukgin** [comment]
> 应该要有todo list 的，还有任务分配，不然容易做重复工

好的，我搞一下，后续如果有什么建议麻烦你告诉我，因为我不太会用github

**Comment by lancelot-Yagami** [comment]
有群方便交流吗？
我可以领几章进行翻译
